env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  Jdbc {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://localhost:55432/test?loggerLevel=OFF"
    user = "test"
    password = "test"
    query = "select id, name, amount, created_at, note, payload from public.st_copy_test order by id"
    partition_column = "id"
    partition_num = 3
    partition_lower_bound = 1
    partition_upper_bound = 4
    use_copy_statement = true
    binary = true
  }
}

sink {
  Console {
    parallelism = 1
  }
}
