#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

env {
  parallelism = 4
  job.mode = "BATCH"
#  checkpoint.interval = 10000
}

source {
  Jdbc {
    # PostgreSQL数据库连接配置
    url = "jdbc:postgresql://192.168.32.2:54321/postgres"
    driver = "org.postgresql.Driver"
    user = "postgres"
    password = "postgres"

    # 启用Copy命令
    use_copy_statement = true

    table_path = "postgres.public.source_table2"
    # 分区配置（用于并行读取）
    # partition_column = "id"

    binary = true

    # 预估行大小（字节数）
    # row_size = 20000
    # 性能优化配置
    ## 每次读取的行数
    fetch_size = 1000000

    ## 分片大小
    split.size = 200000

    # 连接配置
    connection_check_timeout_sec = 30

    # 其他可选配置
#     properties {
#       # PostgreSQL特定属性
#       stringtype = "unspecified"
#      loggerLevel = "OFF"
#     }
  }
}

sink {
  # 输出到控制台进行测试
  Console {
    log.print.data = false
  }

}