######
###### This config file is a demonstration of streaming processing in seatunnel config
######

env {
  parallelism = 8
  job.mode = "BATCH"
}

source {
  # This is an example source plugin **only for test and demonstrate the feature source plugin**
  PostgresCopySource {
#    parallelism = 4
    plugin_output = "PostgresCopy"
    jdbc_url = "jdbc:postgresql://192.168.32.2:54321/postgres"
    database = "postgres"
    username = "postgres"
    password = "postgres"
    table = "source_table2"
    columns = ["*"]
    auto_schema = true
    split_mode = "range"
    split_by = "id"
    split_size = 1000000
    binary = true
  }
}

transform {
}

sink {
  console {
     plugin_input = "PostgresCopy1"
     log.print.data = false
  }
}

#CREATE TABLE users (
#    id SERIAL PRIMARY KEY,
#    username VARCHAR(50) UNIQUE NOT NULL,
#    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
#    is_active BOOLEAN DEFAULT true
#);



#-- 插入多条数据
#INSERT INTO users (username) VALUES
#('jane_smith'),
#('bob_wilson'),
#('alice_brown');

#INSERT INTO users (username) VALUES ('WJR');
# INSERT INTO users (username) VALUES ('WJR2');