######
###### This config file is a demonstration of streaming processing in seatunnel config
######

env {
  parallelism = 2
  job.mode = "STREAMING"
}

source {
  # This is an example source plugin **only for test and demonstrate the feature source plugin**
  PostgresCopySource {
#    parallelism = 4
    plugin_output = "PostgresCopy"
    jdbc_url = "jdbc:postgresql://192.168.32.2:54321/postgres"
    database = "postgres"
    username = "postgres"
    password = "postgres"
    table = "source_table2"
    columns = ["id", "name", "score","created_at"]
    auto_schema = false
    schema = {
          fields {
            id = "bigint"
            #username = "string"
            name = "string"
            score = "DECIMAL"
            created_at = "TIMESTAMP"
          }
        }
    split_mode = "range"
    split_by = "id"
    split_size = 100000  # 将1000000条数据分成10个并发任务
  }
}

transform {
}

sink {
  console {
     plugin_input = "PostgresCopy1"
  }
}

#CREATE TABLE users (
#    id SERIAL PRIMARY KEY,
#    username VARCHAR(50) UNIQUE NOT NULL,
#    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
#    is_active BOOLEAN DEFAULT true
#);



#-- 插入多条数据
#INSERT INTO users (username) VALUES
#('jane_smith'),
#('bob_wilson'),
#('alice_brown');

#INSERT INTO users (username) VALUES ('WJR');
# INSERT INTO users (username) VALUES ('WJR2');